index:
    path:     /
    defaults: { _controller: AppBundle:Index:index }
report_index:
    path:     /report
    defaults: { _controller: AppBundle:Report:index }
githut:
    path:     /githut/{username}
    defaults: { _controller: AppBundle:GitHut:index, username: mylastgame }
    requirements:
        username: '\w+'
githut_profile:
    path:     /githut/profile/{username}
    defaults: { _controller: AppBundle:GitHut:profile }
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]