# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    guzzleHttpClient:
        class: AppBundle\Service\GuzzleHttpClient
        arguments:
            - "@guzzle.client.8p_guzzle_client"
    buzzHttpClient:
            class: AppBundle\Service\BuzzHttpClient
    gitHubApi:
        class: AppBundle\Service\GitHubApi
        arguments:
            - "@guzzleHttpClient"
            #- "@buzzHttpClient"
